/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EnvironmentCreate {
    /// The environment name.
    #[serde(rename = "name")]
    pub name: String,
    /// A description of the environment.  You may find it helpful to document how this environment is used to assist others when they need to maintain software that uses this content.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Environments can inherit from a single parent environment which provides values for parameters when specific environments do not have a value set.  Every organization has one default environment that cannot be removed.
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    /// If parent has RBAC enabled and this field is True, RBAC will be enabled and grants from the parent are copied to this environment.  If parent has RBAC enabled and this field is False, RBAC will be enabled but only the minimal necessary grants will be assigned to the newly created environment.   Not used when RBAC is not enabled for the parent.
    #[serde(rename = "copy_rbac", skip_serializing_if = "Option::is_none")]
    pub copy_rbac: Option<bool>,
}

impl EnvironmentCreate {
    pub fn new(name: String) -> EnvironmentCreate {
        EnvironmentCreate {
            name,
            description: None,
            parent: None,
            copy_rbac: None,
        }
    }
}
