/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeaturesResponse {
    #[serde(rename = "self_hosted")]
    pub self_hosted: bool,
    #[serde(rename = "aws_integration")]
    pub aws_integration: bool,
    #[serde(rename = "azure_integration")]
    pub azure_integration: bool,
    #[serde(rename = "github_integration")]
    pub github_integration: bool,
}

impl FeaturesResponse {
    pub fn new(
        self_hosted: bool,
        aws_integration: bool,
        azure_integration: bool,
        github_integration: bool,
    ) -> FeaturesResponse {
        FeaturesResponse {
            self_hosted,
            aws_integration,
            azure_integration,
            github_integration,
        }
    }
}
