/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Group {
    #[serde(rename = "url")]
    pub url: String,
    /// The unique identifier of a group.
    #[serde(rename = "id")]
    pub id: String,
    /// The group name.
    #[serde(rename = "name")]
    pub name: String,
    /// A description of the group.  You may find it helpful to document how this group is used to assist others when they need to maintain this organization.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "users")]
    pub users: Vec<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: Option<String>,
}

impl Group {
    pub fn new(
        url: String,
        id: String,
        name: String,
        users: Vec<String>,
        created_at: String,
        modified_at: Option<String>,
    ) -> Group {
        Group {
            url,
            id,
            name,
            description: None,
            users,
            created_at,
            modified_at,
        }
    }
}
