/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ImportCreateResponse {
    /// Project parameter values after import
    #[serde(rename = "parameter")]
    pub parameter: Vec<crate::models::ImportParameter>,
}

impl ImportCreateResponse {
    pub fn new(parameter: Vec<crate::models::ImportParameter>) -> ImportCreateResponse {
        ImportCreateResponse { parameter }
    }
}
