/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ObjectTypeEnum {
    #[serde(rename = "AwsIntegration")]
    AwsIntegration,
    #[serde(rename = "Environment")]
    Environment,
    #[serde(rename = "GitHubIntegration")]
    GitHubIntegration,
    #[serde(rename = "Grant")]
    Grant,
    #[serde(rename = "Invitation")]
    Invitation,
    #[serde(rename = "Membership")]
    Membership,
    #[serde(rename = "Organization")]
    Organization,
    #[serde(rename = "Parameter")]
    Parameter,
    #[serde(rename = "ParameterRule")]
    ParameterRule,
    #[serde(rename = "ParameterType")]
    ParameterType,
    #[serde(rename = "ParameterTypeRule")]
    ParameterTypeRule,
    #[serde(rename = "Project")]
    Project,
    #[serde(rename = "Pull")]
    Pull,
    #[serde(rename = "Push")]
    Push,
    #[serde(rename = "ServiceAccount")]
    ServiceAccount,
    #[serde(rename = "Tag")]
    Tag,
    #[serde(rename = "Task")]
    Task,
    #[serde(rename = "Template")]
    Template,
    #[serde(rename = "Value")]
    Value,
    #[serde(rename = "unknown_default_open_api", other)]
    UnknownDefaultOpenApi,
}

impl ToString for ObjectTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::AwsIntegration => String::from("AwsIntegration"),
            Self::Environment => String::from("Environment"),
            Self::GitHubIntegration => String::from("GitHubIntegration"),
            Self::Grant => String::from("Grant"),
            Self::Invitation => String::from("Invitation"),
            Self::Membership => String::from("Membership"),
            Self::Organization => String::from("Organization"),
            Self::Parameter => String::from("Parameter"),
            Self::ParameterRule => String::from("ParameterRule"),
            Self::ParameterType => String::from("ParameterType"),
            Self::ParameterTypeRule => String::from("ParameterTypeRule"),
            Self::Project => String::from("Project"),
            Self::Pull => String::from("Pull"),
            Self::Push => String::from("Push"),
            Self::ServiceAccount => String::from("ServiceAccount"),
            Self::Tag => String::from("Tag"),
            Self::Task => String::from("Task"),
            Self::Template => String::from("Template"),
            Self::Value => String::from("Value"),
            Self::UnknownDefaultOpenApi => String::from("unknown_default_open_api"),
        }
    }
}

impl Default for ObjectTypeEnum {
    fn default() -> ObjectTypeEnum {
        Self::AwsIntegration
    }
}
