/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParameterExport {
    /// The exported parameter body.
    #[serde(rename = "body")]
    pub body: String,
    /// If True, the exported parameters include one or more secrets.
    #[serde(rename = "has_secret")]
    pub has_secret: bool,
}

impl ParameterExport {
    pub fn new(body: String, has_secret: bool) -> ParameterExport {
        ParameterExport { body, has_secret }
    }
}
