/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedUpdateUser {
    /// The threads this user is participating in with ChatGPT.
    #[serde(rename = "chatgpt_threads", skip_serializing_if = "Option::is_none")]
    pub chatgpt_threads: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl PatchedUpdateUser {
    pub fn new() -> PatchedUpdateUser {
        PatchedUpdateUser {
            chatgpt_threads: None,
        }
    }
}
