/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceAccountRekeyRequest {
    /// The date and time the previous API key will expire.
    #[serde(rename = "expire_at", skip_serializing_if = "Option::is_none")]
    pub expire_at: Option<String>,
}

impl ServiceAccountRekeyRequest {
    pub fn new() -> ServiceAccountRekeyRequest {
        ServiceAccountRekeyRequest { expire_at: None }
    }
}
