/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// ValueCreate : A value for a parameter in a given environment.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ValueCreate {
    /// The environment this value is set in.
    #[serde(rename = "environment")]
    pub environment: String,
    /// An external parameter leverages a CloudTruth integration to retrieve content on-demand from an external source.  When this is `false` the value is stored by CloudTruth and considered to be _internal_.  When this is `true`, the `external_fqn` field must be set.
    #[serde(rename = "external", skip_serializing_if = "Option::is_none")]
    pub external: Option<bool>,
    /// The FQN, or Fully-Qualified Name, is the path through the integration to get to the desired content.  This must be present and reference a valid integration when the value is `external`.
    #[serde(rename = "external_fqn", skip_serializing_if = "Option::is_none")]
    pub external_fqn: Option<String>,
    /// If the value is `external`, the content returned by the integration can be reduced by applying a JMESpath expression.  This is valid as long as the content is structured and of a supported format.  JMESpath expressions are supported on `json`, `yaml`, and `dotenv` content.
    #[serde(rename = "external_filter", skip_serializing_if = "Option::is_none")]
    pub external_filter: Option<String>,
    /// This is the content to use when resolving the Value for an internal non-secret, or when storing a secret.  This field cannot be specified when creating or updating an `external` value.
    #[serde(rename = "internal_value", skip_serializing_if = "Option::is_none")]
    pub internal_value: Option<String>,
    /// If `true`, apply template substitution rules to this value.  If `false`, this value is a literal value.  Note: secrets cannot be interpolated.
    #[serde(rename = "interpolated", skip_serializing_if = "Option::is_none")]
    pub interpolated: Option<bool>,
}

impl ValueCreate {
    /// A value for a parameter in a given environment.
    pub fn new(environment: String) -> ValueCreate {
        ValueCreate {
            environment,
            external: None,
            external_fqn: None,
            external_filter: None,
            internal_value: None,
            interpolated: None,
        }
    }
}
