# this is a template for handling cross target RPM generation
# as cargo-generate-rpm does not handle cross targets as well as cargo-deb
# the template is very primitive, so we use sed to do the replacement of the target
[package.metadata.generate-rpm]
assets = [
    { source = "target/TARGET/release/cloudtruth",                  dest = "/usr/bin/cloudtruth",                                  mode = "755" },
    { source = "target/TARGET/release/completions/cloudtruth.bash", dest = "/usr/share/bash-completion/completions/cloudtruth",    mode = "644" },
    { source = "target/TARGET/release/completions/cloudtruth.fish", dest = "/usr/share/fish/vendor_completions.d/cloudtruth.fish", mode = "644" },
    { source = "target/TARGET/release/completions/_cloudtruth",     dest = "/usr/share/zsh/vendor-completions/_cloudtruth",        mode = "644" },
    { source = "README.md",                                         dest = "/usr/share/doc/cloudtruth/README.md",                  mode = "644" }
]
auto-req = "no"

[package.metadata.generate-rpm.requires]
ca-certificates = "*"
