[build.env]
passthrough = [
    "RUST_BACKTRACE"
]

[build.target.x86_64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture linux-x86_64",
    "apt-get update -y && apt-get install -y libssl-dev:linux-x86_64"
]

[build.target.arm-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture linux-armv4",
    "apt-get update -y && apt-get install -y libssl-dev:linux-armv4"
]

[build.target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture linux-aarch64",
    "apt-get update -y && apt-get install -y libssl-dev:linux-aarch64"
]