FROM alpine:3.13
ARG DOWNLOAD_VERSION=""
ENV CT_DOWNLOAD_VERSION=$DOWNLOAD_VERSION
COPY install.sh /tmp/ctinstall.sh
RUN chmod 755 /tmp/ctinstall.sh && /tmp/ctinstall.sh --debug --version "${CT_DOWNLOAD_VERSION}"
CMD cloudtruth --version