---
release-builds:
  - { runner: ubuntu-latest  , target: x86_64-unknown-linux-musl }
  - { runner: ubuntu-latest  , target: arm-unknown-linux-musleabihf }
  - { runner: ubuntu-latest  , target: armv7-unknown-linux-musleabihf }
  - { runner: ubuntu-latest  , target: aarch64-unknown-linux-musl }
  - { runner: ubuntu-latest  , target: aarch64-unknown-linux-gnu }
  - { runner: macos-latest   , target: x86_64-apple-darwin }
  - { runner: macos-latest   , target: aarch64-apple-darwin }
  - { runner: windows-latest , target: x86_64-pc-windows-msvc }
release-tests:
  - os: alpine
    type: docker
    versions:
      - "3.18"
      - "3.17"
      - "3.16"
    platforms:
      - linux/amd64
      - linux/arm64/v8
      - linux/arm/v7
      - linux/arm/v6
  - os: rockylinux
    type: docker
    versions:
      - "9"
      - "8"
  # test CentOS 7 as an approximation of RHEL
  - os: centos
    type: docker
    versions:
      - "7"
  - os: debian
    type: docker
    versions:
      - testing-slim
      - stable-slim
      - oldstable-slim
  - os: ubuntu
    type: docker
    versions:
      - latest
      - rolling
      - devel
  - os: macos
    type: shell
    versions:
      - latest
  - os: windows
    type: powershell
    versions:
      - latest
