FROM debian:testing-slim
ARG DOWNLOAD_AUTH_TOKEN=""
ARG DOWNLOAD_RELEASE_ID=""
ARG DOWNLOAD_VERSION=""
ARG DEBUG=""
ARG INSTALL_PREREQUISITES=""
ENV CT_DOWNLOAD_AUTH_TOKEN=${DOWNLOAD_AUTH_TOKEN}
ENV CT_DOWNLOAD_RELEASE_ID=${DOWNLOAD_RELEASE_ID}
ENV CT_DOWNLOAD_VERSION=${DOWNLOAD_VERSION}
ENV CT_DEBUG=${DEBUG}
ENV CT_INSTALL_PREREQUISITES=${INSTALL_PREREQUISITES}
# fixes apt-get issue on Debian and Ubuntu images where packages were missing
RUN apt-get update
# fixes issue with missing certs on Debian and Ubuntu
RUN apt-get install --yes ca-certificates
COPY ./install.sh /tmp/ctinstall.sh
RUN chmod 755 /tmp/ctinstall.sh && /tmp/ctinstall.sh \
    ${CT_INSTALL_PREREQUISITES:+ --install-prerequisites} \
    ${CT_DEBUG:+ --debug} \
    --version "${CT_DOWNLOAD_VERSION}" \
    ${CT_DOWNLOAD_RELEASE_ID:+ --auth-token "${CT_DOWNLOAD_AUTH_TOKEN}" --release-id "${CT_DOWNLOAD_RELEASE_ID}"}
CMD cloudtruth --version