##### Default configuration for all tests #####
[profile.default]

##### Configuration overrides for integration tests #####
[[profile.default.overrides]]

filter = "kind(test)"

# Retry failed tests
retries = 1

# Define "slow" tests as being over 180 seconds
slow-timeout = { period = "180s" }

##### Configuration for CI runs #####
[profile.ci]

# show skipped tests in report
status-level = "all"

# show failure output immediately as well as at the end
failure-output = "immediate-final"

# continue if a test fails
fail-fast = false
