##### Default configuration for all tests #####
[profile.default]

##### Configuration overrides for integration tests #####
[[profile.default.overrides]]
filter = "kind(test)"

# Retry failed tests
retries = { count = 2, backoff = "fixed", delay = "5s" }

# Define "slow" tests as being over 180 seconds
slow-timeout = { period = "180s", terminate-after = 3 }

##### Configuration for CI runs #####
[profile.ci]

# show passing and failing tests immediately
status-level = "pass"

# show non-passing tests in final summary
final-status-level = "slow"

# continue if a test fails
fail-fast = false
