##### Default configuration for all tests #####
[profile.default]

##### Configuration overrides for integration tests #####
[[profile.default.overrides]]

filter = "kind(test)"

# Retry failed tests
retries = 1

# Define "slow" tests as being over 90 seconds
slow-timeout = { period = "90s" }

##### Configuration for CI runs #####
[profile.ci]

# show skipped tests in logs
status-level = "pass"

# show pass-fail report at end
final-status-level = "slow"

# continue if a test fails
fail-fast = false
