##### Default configuration for all tests #####
[profile.default]

##### Configuration overrides for integration tests #####
[[profile.default.overrides]]
filter = "kind(test)"

# Define "slow" tests as being over 180 seconds
slow-timeout = { period = "240s", terminate-after = 3, grace-period = "30s" }

##### Configuration for CI runs #####
[profile.ci]

# show passing and failing tests immediately in CI
status-level = "pass"

# show non-passing tests in final summary of CI
final-status-level = "slow"

# continue if a test fails in CI
fail-fast = false

##### Configuration overrides for integration tests in CI runs #####
[[profile.ci.overrides]]
filter = "kind(test)"
# Retry failed tests in CI
retries = { count = 2, backoff = "exponential", delay = "10s" }

[[profile.default.overrides]]
filter = "kind(test) & test(test_parameters)"
test-group = "parameter-tests"

[[profile.default.overrides]]
filter = "kind(test) & not test(test_parameters)"
test-group = "non-parameter-tests"


[test-groups]
# limit concurrency of parameter tests to avoid Gateway Timeout errors
non-parameter-tests = { max-threads = 4 }
parameter-tests = { max-threads = 2 }
