[package]
name = "ci"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.69"
maplit = "1.0.2"
peeking_take_while = "1.0.0"
sailfish = "0.6.0"
sailfish-macros = "0.6.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
serde_yaml = "0.9.17"
