---
release-builds:
  - { os: ubuntu-latest  , target: x86_64-unknown-linux-musl   , use-cross: true  }
  - { os: ubuntu-latest  , target: arm-unknown-linux-gnueabihf , use-cross: true  }
  - { os: ubuntu-latest  , target: aarch64-unknown-linux-gnu   , use-cross: true  }
  - { os: macos-latest   , target: x86_64-apple-darwin         , use-cross: false }
  - { os: macos-latest   , target: aarch64-apple-darwin        , use-cross: false }
  - { os: windows-latest , target: x86_64-pc-windows-msvc      , use-cross: false }
release-tests:
  alpine:
    docker: true
    versions:
      - "3.17"
      - "3.16"
      - "3.15"
      - "3.14"
  rockylinux:
    docker: true
    versions:
      - "9"
      - "8"
  debian:
    docker: true
    versions:
      - bullseye-slim
      - buster-slim
      - stretch-slim
  macOS:
    docker: false
    versions:
      - latest
  ubuntu:
    docker: true
    versions:
      - lunar
      - kinetic
      - jammy
      - focal
      - bionic
  windows:
    docker: false
    powershell: true
    versions:
      - latest
