/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditTrailSummary {
    /// The earliest audit record timestamp available.
    #[serde(rename = "earliest")]
    pub earliest: Option<String>,
    /// The total number of audit records available.
    #[serde(rename = "total")]
    pub total: i32,
}

impl AuditTrailSummary {
    pub fn new(earliest: Option<String>, total: i32) -> AuditTrailSummary {
        AuditTrailSummary { earliest, total }
    }
}
