/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AwsServiceEnum {
    #[serde(rename = "s3")]
    S3,
    #[serde(rename = "secretsmanager")]
    Secretsmanager,
    #[serde(rename = "ssm")]
    Ssm,
    #[serde(rename = "unknown_default_open_api", other)]
    UnknownDefaultOpenApi,
}

impl ToString for AwsServiceEnum {
    fn to_string(&self) -> String {
        match self {
            Self::S3 => String::from("s3"),
            Self::Secretsmanager => String::from("secretsmanager"),
            Self::Ssm => String::from("ssm"),
            Self::UnknownDefaultOpenApi => String::from("unknown_default_open_api"),
        }
    }
}

impl Default for AwsServiceEnum {
    fn default() -> AwsServiceEnum {
        Self::S3
    }
}
