/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AwsRegionEnum {
    #[serde(rename = "af-south-1")]
    AfSouth1,
    #[serde(rename = "ap-east-1")]
    ApEast1,
    #[serde(rename = "ap-northeast-1")]
    ApNortheast1,
    #[serde(rename = "ap-northeast-2")]
    ApNortheast2,
    #[serde(rename = "ap-northeast-3")]
    ApNortheast3,
    #[serde(rename = "ap-south-1")]
    ApSouth1,
    #[serde(rename = "ap-southeast-1")]
    ApSoutheast1,
    #[serde(rename = "ap-southeast-2")]
    ApSoutheast2,
    #[serde(rename = "ca-central-1")]
    CaCentral1,
    #[serde(rename = "cn-north-1")]
    CnNorth1,
    #[serde(rename = "cn-northwest-1")]
    CnNorthwest1,
    #[serde(rename = "eu-central-1")]
    EuCentral1,
    #[serde(rename = "eu-north-1")]
    EuNorth1,
    #[serde(rename = "eu-south-1")]
    EuSouth1,
    #[serde(rename = "eu-west-1")]
    EuWest1,
    #[serde(rename = "eu-west-2")]
    EuWest2,
    #[serde(rename = "eu-west-3")]
    EuWest3,
    #[serde(rename = "me-south-1")]
    MeSouth1,
    #[serde(rename = "sa-east-1")]
    SaEast1,
    #[serde(rename = "us-east-1")]
    UsEast1,
    #[serde(rename = "us-east-2")]
    UsEast2,
    #[serde(rename = "us-west-1")]
    UsWest1,
    #[serde(rename = "us-west-2")]
    UsWest2,
}

impl ToString for AwsRegionEnum {
    fn to_string(&self) -> String {
        match self {
            Self::AfSouth1 => String::from("af-south-1"),
            Self::ApEast1 => String::from("ap-east-1"),
            Self::ApNortheast1 => String::from("ap-northeast-1"),
            Self::ApNortheast2 => String::from("ap-northeast-2"),
            Self::ApNortheast3 => String::from("ap-northeast-3"),
            Self::ApSouth1 => String::from("ap-south-1"),
            Self::ApSoutheast1 => String::from("ap-southeast-1"),
            Self::ApSoutheast2 => String::from("ap-southeast-2"),
            Self::CaCentral1 => String::from("ca-central-1"),
            Self::CnNorth1 => String::from("cn-north-1"),
            Self::CnNorthwest1 => String::from("cn-northwest-1"),
            Self::EuCentral1 => String::from("eu-central-1"),
            Self::EuNorth1 => String::from("eu-north-1"),
            Self::EuSouth1 => String::from("eu-south-1"),
            Self::EuWest1 => String::from("eu-west-1"),
            Self::EuWest2 => String::from("eu-west-2"),
            Self::EuWest3 => String::from("eu-west-3"),
            Self::MeSouth1 => String::from("me-south-1"),
            Self::SaEast1 => String::from("sa-east-1"),
            Self::UsEast1 => String::from("us-east-1"),
            Self::UsEast2 => String::from("us-east-2"),
            Self::UsWest1 => String::from("us-west-1"),
            Self::UsWest2 => String::from("us-west-2"),
        }
    }
}

impl Default for AwsRegionEnum {
    fn default() -> AwsRegionEnum {
        Self::AfSouth1
    }
}
