/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// BackupParameterType : Parameter type (and rule) data at a point in time.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BackupParameterType {
    #[serde(rename = "rules")]
    pub rules: ::std::collections::HashMap<String, crate::models::BackupParameterRule>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "parent")]
    pub parent: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl BackupParameterType {
    /// Parameter type (and rule) data at a point in time.
    pub fn new(
        rules: ::std::collections::HashMap<String, crate::models::BackupParameterRule>,
        name: String,
        parent: String,
    ) -> BackupParameterType {
        BackupParameterType {
            rules,
            name,
            parent,
            description: None,
        }
    }
}
