/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// BackupDataSnapshot : Environment, parameter-type, and project (including parameters and values) data at a point in time.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BackupDataSnapshot {
    #[serde(rename = "environments")]
    pub environments: ::std::collections::HashMap<String, crate::models::BackupEnvironment>,
    #[serde(rename = "types")]
    pub types: ::std::collections::HashMap<String, crate::models::BackupParameterType>,
    #[serde(rename = "projects")]
    pub projects: ::std::collections::HashMap<String, crate::models::BackupProject>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl BackupDataSnapshot {
    /// Environment, parameter-type, and project (including parameters and values) data at a point in time.
    pub fn new(environments: ::std::collections::HashMap<String, crate::models::BackupEnvironment>, types: ::std::collections::HashMap<String, crate::models::BackupParameterType>, projects: ::std::collections::HashMap<String, crate::models::BackupProject>, timestamp: String) -> BackupDataSnapshot {
        BackupDataSnapshot {
            environments,
            types,
            projects,
            timestamp,
        }
    }
}


