/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeaturesResponse {
    #[serde(rename = "self_hosted")]
    pub self_hosted: bool,
}

impl FeaturesResponse {
    pub fn new(self_hosted: bool) -> FeaturesResponse {
        FeaturesResponse { self_hosted }
    }
}
