/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ModeEnum {
    #[serde(rename = "mapped")]
    Mapped,
    #[serde(rename = "pattern")]
    Pattern,
}

impl ToString for ModeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Mapped => String::from("mapped"),
            Self::Pattern => String::from("pattern"),
        }
    }
}

impl Default for ModeEnum {
    fn default() -> ModeEnum {
        Self::Mapped
    }
}
