/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ObjectTypeEnum {
    #[serde(rename = "Environment")]
    Environment,
    #[serde(rename = "Integration")]
    Integration,
    #[serde(rename = "Invitation")]
    Invitation,
    #[serde(rename = "Membership")]
    Membership,
    #[serde(rename = "Organization")]
    Organization,
    #[serde(rename = "Parameter")]
    Parameter,
    #[serde(rename = "Project")]
    Project,
    #[serde(rename = "ServiceAccount")]
    ServiceAccount,
    #[serde(rename = "Template")]
    Template,
    #[serde(rename = "Value")]
    Value,
}

impl ToString for ObjectTypeEnum {
    fn to_string(&self) -> String {
        match self {
            Self::Environment => String::from("Environment"),
            Self::Integration => String::from("Integration"),
            Self::Invitation => String::from("Invitation"),
            Self::Membership => String::from("Membership"),
            Self::Organization => String::from("Organization"),
            Self::Parameter => String::from("Parameter"),
            Self::Project => String::from("Project"),
            Self::ServiceAccount => String::from("ServiceAccount"),
            Self::Template => String::from("Template"),
            Self::Value => String::from("Value"),
        }
    }
}
