/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParameterTypeCreate {
    /// The parameter type name.
    #[serde(rename = "name")]
    pub name: String,
    /// A description of the parameter type, provide documentation on how to use this type here.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// All types must derive, either directly or indirectly, from one of the CloudTruth built-in types.   This is the ParameterType that this type is derived from.
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
}

impl ParameterTypeCreate {
    pub fn new(name: String) -> ParameterTypeCreate {
        ParameterTypeCreate {
            name,
            description: None,
            parent: None,
        }
    }
}
