/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// ParameterDuality : Details about a parameter at two timepoints.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParameterDuality {
    #[serde(rename = "t1")]
    pub t1: Box<crate::models::Parameter>,
    #[serde(rename = "t2")]
    pub t2: Box<crate::models::Parameter>,
}

impl ParameterDuality {
    /// Details about a parameter at two timepoints.
    pub fn new(t1: crate::models::Parameter, t2: crate::models::Parameter) -> ParameterDuality {
        ParameterDuality {
            t1: Box::new(t1),
            t2: Box::new(t2),
        }
    }
}
