/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// ParameterDuality : Details about a parameter at two timepoints.  If t1 or t2 is null then the parameter did not exist at that timepoint.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParameterDuality {
    #[serde(rename = "t1")]
    pub t1: Option<Box<crate::models::Parameter>>,
    #[serde(rename = "t2")]
    pub t2: Option<Box<crate::models::Parameter>>,
}

impl ParameterDuality {
    /// Details about a parameter at two timepoints.  If t1 or t2 is null then the parameter did not exist at that timepoint.
    pub fn new(t1: Option<crate::models::Parameter>, t2: Option<crate::models::Parameter>) -> ParameterDuality {
        ParameterDuality {
            t1: Box::new(t1),
            t2: Box::new(t2),
        }
    }
}


