/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// ParameterUpdate : A single parameter inside of a project.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParameterUpdate {
    #[serde(rename = "id")]
    pub id: String,
    /// The parameter name.
    #[serde(rename = "name")]
    pub name: String,
    /// A description of the parameter.  You may find it helpful to document how this parameter is used to assist others when they need to maintain software that uses this content.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Indicates if this content is secret or not.  External values are inspected on-demand to ensure they align with the parameter's secret setting and if they do not, those external values are not allowed to be used.
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<bool>,
    /// The type of this Parameter.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// The project url.
    #[serde(rename = "project")]
    pub project: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: Option<String>,
}

impl ParameterUpdate {
    /// A single parameter inside of a project.
    pub fn new(id: String, name: String, project: String, created_at: String, modified_at: Option<String>) -> ParameterUpdate {
        ParameterUpdate {
            id,
            name,
            description: None,
            secret: None,
            _type: None,
            project,
            created_at,
            modified_at,
        }
    }
}


