/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchedInvitation {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The unique identifier of an invitation.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The email address of the user to be invited.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The role that the user will have in the organization, should the user accept.
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Box<crate::models::RoleEnum>>,
    /// The user that created the invitation.
    #[serde(rename = "inviter", skip_serializing_if = "Option::is_none")]
    pub inviter: Option<String>,
    /// The name of the user that created the invitation.
    #[serde(rename = "inviter_name", skip_serializing_if = "Option::is_none")]
    pub inviter_name: Option<String>,
    /// The current state of the invitation.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// Additional details about the state of the invitation.
    #[serde(rename = "state_detail", skip_serializing_if = "Option::is_none")]
    pub state_detail: Option<String>,
    /// The resulting membership, should the user accept.
    #[serde(rename = "membership", skip_serializing_if = "Option::is_none")]
    pub membership: Option<String>,
}

impl PatchedInvitation {
    pub fn new() -> PatchedInvitation {
        PatchedInvitation {
            url: None,
            id: None,
            email: None,
            role: None,
            inviter: None,
            inviter_name: None,
            state: None,
            state_detail: None,
            membership: None,
        }
    }
}
