/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// TemplateUpdate : A parameter template in a given project, optionally instantiated against an environment.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TemplateUpdate {
    #[serde(rename = "id")]
    pub id: String,
    /// The template name.
    #[serde(rename = "name")]
    pub name: String,
    /// ('A description of the template.  You may find it helpful to document how this template is used to assist others when they need to maintain software that uses this content.',)
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// If true, the `body` field has undergone evaluation.
    #[serde(rename = "evaluated")]
    pub evaluated: bool,
    /// The content of the template.  Use mustache-style templating delimiters of `{{` and `}}` to reference parameter values by name for substitution into the template result.
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: Option<String>,
}

impl TemplateUpdate {
    /// A parameter template in a given project, optionally instantiated against an environment.
    pub fn new(id: String, name: String, evaluated: bool, created_at: String, modified_at: Option<String>) -> TemplateUpdate {
        TemplateUpdate {
            id,
            name,
            description: None,
            evaluated,
            body: None,
            created_at,
            modified_at,
        }
    }
}


