/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your parameters and secrets making them easier to manage and use.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// Template : A parameter template in a given project, optionally instantiated against an environment.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Template {
    #[serde(rename = "url")]
    pub url: String,
    /// A unique identifier for the template.
    #[serde(rename = "id")]
    pub id: String,
    /// The template name.
    #[serde(rename = "name")]
    pub name: String,
    /// A description of the template.  You may find it helpful to document how this template is used to assist others when they need to maintain software that uses this content.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The content of the template.  Use mustache-style templating delimiters of `{{` and `}}` to reference parameter values by name for substitution into the template result.
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "parameters")]
    pub parameters: Vec<String>,
    /// If True, this template contains secrets.
    #[serde(rename = "has_secret")]
    pub has_secret: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "modified_at")]
    pub modified_at: String,
}

impl Template {
    /// A parameter template in a given project, optionally instantiated against an environment.
    pub fn new(
        url: String,
        id: String,
        name: String,
        parameters: Vec<String>,
        has_secret: bool,
        created_at: String,
        modified_at: String,
    ) -> Template {
        Template {
            url,
            id,
            name,
            description: None,
            body: None,
            parameters,
            has_secret,
            created_at,
            modified_at,
        }
    }
}
