/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// TemplateTimelineEntryTemplate : Helper methods for all views or serializers that expose template concepts.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TemplateTimelineEntryTemplate {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "ledger_id")]
    pub ledger_id: String,
    /// The parameter name.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The content of the template.  Use mustache-style templating delimiters of `{{` and `}}` to reference parameter values by name for substitution into the template result.
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
}

impl TemplateTimelineEntryTemplate {
    /// Helper methods for all views or serializers that expose template concepts.
    pub fn new(id: String, ledger_id: String, name: String) -> TemplateTimelineEntryTemplate {
        TemplateTimelineEntryTemplate {
            id,
            ledger_id,
            name,
            description: None,
            body: None,
        }
    }
}


