/*
 * CloudTruth Management API
 *
 * CloudTruth centralizes your configuration parameters and secrets making them easier to manage and use as a team.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@cloudtruth.com
 * Generated by: https://openapi-generator.tech
 */

/// TemplateTimelineEntry : Details about a single change.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemplateTimelineEntry {
    #[serde(rename = "history_date")]
    pub history_date: String,
    #[serde(rename = "history_type")]
    pub history_type: Box<crate::models::HistoryTypeEnum>,
    /// The unique identifier of a user.
    #[serde(rename = "history_user", skip_serializing_if = "Option::is_none")]
    pub history_user: Option<String>,
    /// The template record as it was when archived for history.
    #[serde(rename = "history_template")]
    pub history_template: Box<crate::models::TemplateTimelineEntryTemplate>,
}

impl TemplateTimelineEntry {
    /// Details about a single change.
    pub fn new(
        history_date: String,
        history_type: crate::models::HistoryTypeEnum,
        history_template: crate::models::TemplateTimelineEntryTemplate,
    ) -> TemplateTimelineEntry {
        TemplateTimelineEntry {
            history_date,
            history_type: Box::new(history_type),
            history_user: None,
            history_template: Box::new(history_template),
        }
    }
}
