# A callable workflow for CLI builds
# Stores the build artifact at the given artifact ID
---
name: Build
on:
  workflow_call:
    inputs:
      artifactId:
        description: The artifact ID used to store the build artifact with actions/upload-artifact
        type: string
        required: true
      runsOn:
        description: The runner to run the workflow on
        type: string
        default: ubuntu-latest
      ref:
        description: the git ref to checkout from cloudtruth-cli
        type: string
      buildOptions:
        description: options to pass to the Cargo build
        type: string
        default: --all-features --workspace --lib --bins --tests
      testOptions:
        description: options to pass to the Cargo tests
        type: string
        default: --all-features --workspace --lib --bins
      rustCacheKey:
        description: cache ID to use for rust-cache
        type: string
        default: v0-cloudtruth

env:
  CI: true
  ARCHIVE_FILE: integration-test-archive.tar.zst
  RUST_BACKTRACE: 1
  RUSTFLAGS: ${{ inputs.runsOn == 'macos-latest' && '-C split-debuginfo=packed' || ''}}

jobs:
  build:
    name: CLI Build
    runs-on: ${{ inputs.runsOn }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - run: sh cicd/scripts/install-rust.sh

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ inputs.rustCacheKey }}

      - uses: taiki-e/install-action@cargo-nextest

      - name: Clean Debug Files
        if: ${{ !contains(runner.os, 'Linux') }}
        run: |
          find target -path '*/*.dSYM/*' -or -name '*.pdb' -delete

      - name: Build and Create Test Archive
        run: cargo nextest archive ${{ inputs.buildOptions }} --archive-file $ARCHIVE_FILE

      - name: Unit Tests
        run: cargo nextest run --profile ci ${{ inputs.testOptions }}

      - name: Add Debug Files to Test Archive
        if: ${{ !contains(runner.os, 'Linux') }}
        run: |
          DEBUG_FILES=$(find target -path '*/cloudtruth*.dSYM/*' -or -path '*/test_*.dSYM/*' -or -name '*.pdb')
          if [ -n "$DEBUG_FILES" ]; then
            zstd -d $ARCHIVE_FILE -o tmp-archive.tar
            tar rvf tmp-archive.tar $DEBUG_FILES
            zstd --rm -f tmp-archive.tar -o $ARCHIVE_FILE
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifactId }}
          if-no-files-found: ignore
          path: |
            ./integration-test-archive.tar.zst

