---
on:
  release:
    types: [prereleased]

name: 'Check Pre-Release'

jobs:
  test-release:
    name: Test Release
    uses: ./.github/workflows/test-release.yml
    with:
      releaseVersion: 1.1.8 #${{ event.release.tag_name }}
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY}}