---
on:
  release:
    types: [prereleased]

name: 'Check Pre-Release'
run-name: 'Check Pre-Release ${{events.release.tag_name }}'

jobs:
  test-release:
    name: Test Release
    if: ${{ !contains('staging', github.event.release.tag_name) }}
    uses: ./.github/workflows/test-release.yml
    with:
      releaseVersion: ${{ event.release.tag_name }}
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}

  test-staging-release:
    name: Test Staging Release
    if: ${{ contains('staging', github.event.release.tag_name) }}
    uses: ./.github/workflows/test-release.yml
    with:
      releaseVersion: ${{ event.release.tag_name }}
      serverUrl: https://api.staging.cloudtruth.io
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}