---
on:
  release:
    types: [prereleased]

name: 'Check Pre-Release'

jobs:
  test-alpine:
    runs-on: ubuntu-latest
    env:
      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla
      CT_VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: alpine-3.13
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.alpine-3.13 \
             -t cloudtruth:alpine-3.13
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:alpine-3.13 cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
      - name: alpine-3.12
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.alpine-3.12 \
             -t cloudtruth:alpine-3.12
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:alpine-3.12 cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
  test-rockylinux:
    runs-on: ubuntu-latest
    env:
      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla
      CT_VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: rockylinux-8
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.rockylinux-8 \
             -t cloudtruth:rockylinux-8
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:rockylinux-8 cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
  test-debian:
    runs-on: ubuntu-latest
    env:
      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla
      CT_VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: debian-bullseye-slim
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.debian-bullseye-slim \
             -t cloudtruth:debian-bullseye-slim
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:debian-bullseye-slim cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
      - name: debian-buster-slim
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.debian-buster-slim \
             -t cloudtruth:debian-buster-slim
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:debian-buster-slim cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
      - name: debian-jessie-slim
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.debian-jessie-slim \
             -t cloudtruth:debian-jessie-slim
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:debian-jessie-slim cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
  test-macOS:
    runs-on: macOS-latest
    env:
      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla
      CT_VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: macOS-latest
        run: |
          sudo ./install.sh --version "${CT_VERSION}"
          cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep "${CT_TEST_PARAM}" | grep "${CT_TEST_VALUE}"

  test-ubuntu:
    runs-on: ubuntu-latest
    env:
      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla
      CT_VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1


      - name: ubuntu-focal
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.ubuntu-focal \
             -t cloudtruth:ubuntu-focal
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:ubuntu-focal cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
      - name: ubuntu-bionic
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.ubuntu-bionic \
             -t cloudtruth:ubuntu-bionic
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:ubuntu-bionic cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
      - name: ubuntu-xenial
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.ubuntu-xenial \
             -t cloudtruth:ubuntu-xenial
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:ubuntu-xenial cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
      - name: ubuntu-trusty
        run: |
          docker build . \
            --build-arg DOWNLOAD_VERSION="${CT_VERSION}" \
             -f build/docker/prerelease/Dockerfile.ubuntu-trusty \
             -t cloudtruth:ubuntu-trusty
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:ubuntu-trusty cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}
  test-windows:
    runs-on: windows-latest
    env:
      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla
      CT_VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: windows-latest
        shell: pwsh
        run: |
          $InformationPreference = 'Continue'
          New-Alias grep findstr
          $ctExe = .\install.ps1 -version "$ENV:CT_VERSION"
          & $ctExe --project "$ENV:CT_TEST_PROJECT" parameters list -v | grep "$ENV:CT_TEST_PARAM" | grep "$ENV:CT_TEST_VALUE"