name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: cloudtruth/cli-build-action@v1
        with:
          components: rustfmt, clippy
          skipBuild: true
          skipUnitTests: true
          cacheKey: v0-cli-lint

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: client

      - run: cargo fmt --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          name: Clippy Check
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

  test:
    name: CI Test
    uses: ./.github/workflows/test.yml

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            options: --before test_parameter
          - os: ubuntu-latest
            options: --after test_parameter --before test_project
          - os: windows-latest
            options: --after test_project

    with:
      runsOn: ${{ matrix.os }}
      serverUrl: https://api.staging.cloudtruth.io
      testRunnerOptions: --exclude backup ${{ matrix.options }}

    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}
