name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml      

  test:
    name: Test
    uses: ./.github/workflows/test-staging.yml

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            options: --before test_parameter
          - os: ubuntu-latest
            options: --after test_parameter --before test_project
          - os: windows-latest
            options: --after test_project

    with:
      runsOn: ${{ matrix.os }}
      testRunnerOptions: ${{ matrix.options }}
    secrets: inherit

