name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CI: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  # build:
  #   name: Build
  #   uses: ./.github/workflows/build.yml
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [macos-latest, ubuntu-latest, windows-latest]
  #   with:
  #     runsOn: ${{ matrix.os }}
  #     artifactId: cloudtruth-ci-${{ matrix.os }}

  test:
    name: Test
    uses: ./.github/workflows/test-staging.yml
    # needs: [build]

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            options: --before test_parameter
          - os: ubuntu-latest
            options: --after test_parameter --before test_project
          - os: windows-latest
            options: --after test_project

    with:
      runsOn: ${{ matrix.os }}
      # artifactId: cloudtruth-ci-${{ matrix.os }}
      testRunnerOptions: ${{ matrix.options }}
      releaseVersion: staging
    secrets: inherit

