name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CI: true
  RUST_BACKTRACE: 1

  # these are to run against staging
  CLOUDTRUTH_SERVER_URL: https://api.staging.cloudtruth.io
  CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}

  PART_A_END: test_parameter
  PART_C_START: test_project

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: cloudtruth/cli-build-action@v1
        with:
          components: rustfmt, clippy
          skipBuild: true
          skipUnitTests: true
          cacheKey: v0-cli-lint

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: client

      - run: cargo fmt --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          name: Clippy Check
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

  test:
    name: Test
    uses: cloudtruth/cloudtruth-cli/.github/workflows/test.yml@${{ github.ref }}
    strategy:
      fail-fast: false
      matrix:
        partitions:
          - os: macos-latest
            options: --before ${{ env.PART_A_END }}
          - os: ubuntu-latest
            options: --after ${{ env.PART_A_END }} --before ${{ env.PART_C_START }} 
          - os: windows-latest
            options: ${{ env.PART_C_START }} 
    with:
      runs-on: ${{ matrix.os }}
      serverUrl: ${{ env.CLOUDTRUTH_SERVER_URL }}
      testRunnerOptions: --exclude backup ${{ matrix.partitions.options }}

    secrets:
      CLOUDTRUTH_API_KEY: ${{ env.CLOUDTRUTH_API_KEY }}
