name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CI: true
  RUST_BACKTRACE: 1
  # This needs to match the RUST_VERSION in create-draft-release.yml.
  RUST_VERSION: 1.57.0

  # These are based on pre-configured integrations in the CLI CI account.
  CLOUDTRUTH_TEST_BROKEN_PROJECT: proj-int-broken
  CLOUDTRUTH_TEST_BROKEN_TEMPLATE: temp-int-broken
  CLOUDTRUTH_TEST_BROKEN_PARAM1: param1
  CLOUDTRUTH_TEST_BROKEN_PARAM2: param2
  CLOUDTRUTH_TEST_BROKEN_PARAM3: param3
  CLOUDTRUTH_TEST_BROKEN_PARAM4: param4
  CLOUDTRUTH_TEST_BROKEN_VALUE1: value1
  CLOUDTRUTH_TEST_BROKEN_VALUE2: King
  CLOUDTRUTH_TEST_BROKEN_VALUE3: voluptas
  CLOUDTRUTH_TEST_BROKEN_JMES2: speicla.beef_brocolli
  CLOUDTRUTH_TEST_BROKEN_JMES3: numquam.doloremque
  CLOUDTRUTH_TEST_BROKEN_FQN2: github://rickporter-tuono/hello-world/master/jade.yml
  CLOUDTRUTH_TEST_BROKEN_FQN3: github://rickporter-tuono/cloudtruth_test/trimmed/more_config/anotherconfig.yaml

  CLOUDTRUTH_TEST_EXPLORE_FQN: github://rickporter-tuono/cloudtruth_test/main/short.yaml
  CLOUDTRUTH_TEST_EXPLORE_JMES: speicla.POrk_Egg_Foo_Young
  CLOUDTRUTH_TEST_EXPLORE_VALUE: Healey

  CLOUDTRUTH_TEST_PARAMETERS_FQN: github://rickporter-tuono/cloudtruth_test/my-branch/short.yaml
  CLOUDTRUTH_TEST_PARAMETERS_JMES: speicla.POrk_Egg_Foo_Young

  CLOUDTRUTH_TEST_TEMPLATE_FQN: github://rickporter-tuono/cloudtruth_test/main/ci_test_template.txt
  CLOUDTRUTH_TEST_TEMPLATE_PARAM1: my-param-name

  CLOUDTRUTH_TEST_BASIC_INTEGRATION_NAME: ct-stage-write@943604981792
  CLOUDTRUTH_TEST_BASIC_BAD_INTEGRATION_NAME: my-missing-integration

  CLOUDTRUTH_TEST_PUSH_INTEGRATION_NAME: ct-stage-write@943604981792
  CLOUDTRUTH_TEST_PUSH_BAD_INTEGRATION_NAME: my-missing-integration

  CLOUDTRUTH_TEST_IMPORT_INTEGRATION_NAME: ct-stage-write@943604981792
  CLOUDTRUTH_TEST_IMPORT_BAD_INTEGRATION_NAME: my-missing-integration

  CLOUDTRUTH_TEST_COMPLETE_INTEGRATION_NAME: ct-stage-write@943604981792

  PART_A_END: test_parameter
  PART_C_START: test_project

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Install Rust
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ steps.rust.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Show Rust version and platform details
        run: rustc --version --verbose

      - run: cargo fmt --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          name: Clippy Check
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -D warnings

  test:
    name: Test
    runs-on: ${{ matrix.os }}

    env:
      # these are to run against staging
      CLOUDTRUTH_SERVER_URL: https://api.staging.cloudtruth.io
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Show Rust version and platform details
        run: rustc --version --verbose

      - run: cargo build
      - run: cargo test
      - run: make test_prerequisites

      - name: Integration Test - Part A
        env:
          OS: ${{ runner.os }}
        if: runner.os == 'macOs'
        run: |
          cd tests/pytest
          python3 live_test.py --job-id "${OS}-${GITHUB_RUN_NUMBER}" --before ${{ env.PART_A_END }}

      - name: Integration Test - Part B
        env:
          OS: ${{ runner.os }}
        if: runner.os == 'Linux'
        run: |
          cd tests/pytest
          python3 live_test.py --job-id "${OS}-${GITHUB_RUN_NUMBER}" --after ${{ env.PART_A_END }} --before ${{ env.PART_C_START }}

      - name: Integration Test - Part C
        env:
          OS: ${{ runner.os }}
        if: runner.os == 'Windows'
        run: |
          cd tests\pytest
          py live_test.py --job-id "$ENV:OS-$ENV:GITHUB_RUN_NUMBER" --after ${{ env.PART_C_START }}
