name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Cancel in-progress CI runs from the same branch
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    with:
      runsOn: ${{ matrix.os }}
      artifactId: cloudtruth-ci-${{ matrix.os }}

  test:
    name: Test
    uses: ./.github/workflows/test-staging.yml
    needs: [build]
    concurrency: ${{ github.workflow_ref }}-${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            options: --partition hash:1/3
          - os: ubuntu-latest
            options: --partition hash:2/3
          - os: windows-latest
            options: --partition hash:3/3

    with:
      runsOn: ${{ matrix.os }}
      artifactId: cloudtruth-ci-${{ matrix.os }}
      testRunnerOptions: ${{ matrix.options }} -E 'kind(test)'
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CT_STAGING_CI_ADMIN_API_KEY }}
