---
name: Create Draft Release
run-name: Create Draft Release (${{ github.ref_name }})

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-?**'

env:
  CI: true
  RUST_BACKTRACE: 1

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cargo and tag version alignment
        env:
          TAG_VERSION: ${{ github.ref_name }}
        run: |
          CARGO_VERSION=$(grep "version = " Cargo.toml | head -n 1 | cut -d'"' -f2)
          echo "CARGO_VERSION=${CARGO_VERSION}"
          echo "TAG_VERSION=${TAG_VERSION}"
          echo "${TAG_VERSION}" | grep "${CARGO_VERSION}"

    outputs:
      releaseId: ${{ steps.release.outputs.id }}
      releaseUploadUrl: ${{ steps.release.outputs.upload_url }}

  build-release:
    name: Build Release
    needs: create-release
    uses: ./.github/workflows/build-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseUploadUrl: ${{ needs.create-release.outputs.releaseUploadUrl }}
    secrets: inherit

  test-release:
    name: Test Release
    needs: [create-release, build-release]
    uses: ./.github/workflows/test-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseVersion: ${{ github.ref_name }}
    secrets: inherit

  cleanup:
    name: Rollback on Failure
    runs-on: ubuntu-latest
    needs: [create-release, test-release]
    if: failure() && contains(github.ref, 'test')
    steps:
      - uses: author/action-rollback@stable
        if: needs.create_release.outputs.releaseId != ''
        with:
          release_id: ${{ needs.create_release.outputs.releaseId }}
          tag: ${{ github.ref }}
          #  If the release does not exist but the tag does, setting this to true will remove the tag.
          delete_orphan_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
