# This is a "scratch" test  for developers to play with.
#
# It only runs on Ubuntu, unlike the nightly that runs on several platforms.
---
name: Dev
on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: windows-latest

    env:
      # TODO: modify this filter to focus testing
      CLOUDTRUTH_TEST_FILTER: parameter_drift

      # these show the commands and the output from the commands
      CLOUDTRUTH_TEST_EXTRA_ARGS: --log-command --log-output

      # these are to run against staging
      CLOUDTRUTH_SERVER_URL: https://api.staging.cloudtruth.io
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}
      RUST_BACKTRACE: 1
      RUST_VERSION: 1.57.0

      # These are based on pre-configured integrations in the CLI CI account.
      CLOUDTRUTH_TEST_BROKEN_PROJECT: proj-int-broken
      CLOUDTRUTH_TEST_BROKEN_TEMPLATE: temp-int-broken
      CLOUDTRUTH_TEST_BROKEN_PARAM1: param1
      CLOUDTRUTH_TEST_BROKEN_PARAM2: param2
      CLOUDTRUTH_TEST_BROKEN_PARAM3: param3
      CLOUDTRUTH_TEST_BROKEN_PARAM4: param4
      CLOUDTRUTH_TEST_BROKEN_VALUE1: value1
      CLOUDTRUTH_TEST_BROKEN_VALUE2: King
      CLOUDTRUTH_TEST_BROKEN_VALUE3: voluptas
      CLOUDTRUTH_TEST_BROKEN_JMES2: speicla.beef_brocolli
      CLOUDTRUTH_TEST_BROKEN_JMES3: numquam.doloremque
      CLOUDTRUTH_TEST_BROKEN_FQN2: github://cloudtruth/another-test-repo/main/jade.yaml
      CLOUDTRUTH_TEST_BROKEN_FQN3: github://cloudtruth/github-integration-test-repo/trimmed/more_config/anotherconfig.yaml

      CLOUDTRUTH_TEST_EXPLORE_FQN: github://cloudtruth/github-integration-test-repo/main/short.yaml
      CLOUDTRUTH_TEST_EXPLORE_JMES: speicla.POrk_Egg_Foo_Young
      CLOUDTRUTH_TEST_EXPLORE_VALUE: Healey

      CLOUDTRUTH_TEST_PARAMETERS_FQN: github://cloudtruth/github-integration-test-repo/my-branch/short.yaml
      CLOUDTRUTH_TEST_PARAMETERS_JMES: speicla.POrk_Egg_Foo_Young

      CLOUDTRUTH_TEST_TEMPLATE_FQN: github://cloudtruth/github-integration-test-repo/main/ci_test_template.txt
      CLOUDTRUTH_TEST_TEMPLATE_PARAM1: my-param-name

      CLOUDTRUTH_TEST_BASIC_INTEGRATION_NAME: ct-stage-write@943604981792
      CLOUDTRUTH_TEST_BASIC_BAD_INTEGRATION_NAME: my-missing-integration

      CLOUDTRUTH_TEST_PUSH_INTEGRATION_NAME: ct-stage-write@943604981792
      CLOUDTRUTH_TEST_PUSH_BAD_INTEGRATION_NAME: my-missing-integration

      CLOUDTRUTH_TEST_IMPORT_INTEGRATION_NAME: ct-stage-write@943604981792
      CLOUDTRUTH_TEST_IMPORT_BAD_INTEGRATION_NAME: my-missing-integration

      CLOUDTRUTH_TEST_COMPLETE_INTEGRATION_NAME: ct-stage-write@943604981792

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Show Rust version and platform details
        run: rustc --version --verbose

      - run: cargo build

      - name: Filtered integration Test
        env:
          OS: ${{ runner.os }}
        run: |
          cd tests/pytest
          python3 live_test.py --job-id "dev-${GITHUB_RUN_NUMBER}" ${{ env.CLOUDTRUTH_TEST_EXTRA_ARGS }} --filter ${{ env.CLOUDTRUTH_TEST_FILTER }}
