name: Lint
on:
  workflow_dispatch:
    inputs:
      ref:
        description: the git ref to checkout from cloudtruth-cli
        type: string
      rustCacheKey:
        description: cache ID to use for rust-cache
        type: string
        default: v0-cli-lint
  workflow_call:
    inputs:
      ref:
        description: the git ref to checkout from cloudtruth-cli
        type: string
      rustCacheKey:
        description: cache ID to use for rust-cache
        type: string
        default: v0-cli-lint
env:
  CI: true
jobs:
  lint:
    name: CLI Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: cloudtruth/cloudtruth-cli
          ref: ${{ inputs.ref }}

      - shell: bash
        run: sh ci/scripts/install-rust.sh

      - shell: bash
        run: rustup component add rustfmt clippy

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ inputs.rustCacheKey }}
          shared-key: ${{ runner.os }}

      - run: cargo fmt --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          name: Clippy Check
          token: ${{ github.token }}
          args: --all-features -- -D warnings

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: |
            client
            target
