---
name: Nightly Release

on:
  workflow_dispatch:
  schedule:
    # Run builds on midnight EST
    - cron: '0 5 * * *'

jobs:
  create-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
  
    steps:
      - name: Create tag name
        shell: bash
        run: |
          DATE="$(date +%d-%m-%Y)"
          echo DATE=$DATE >> $GITHUB_ENV
          echo TAG_NAME=nightly-$DATE >> $GITHUB_ENV
          echo "RELEASE_NAME=Nightly ($DATE)" >> $GITHUB_ENV

      - name: Create Draft Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # allow overwriting
          updateOnlyUnreleased: true # prevent modifying any non-draft non-prerelease
          removeArtifacts: true # deletes any existing artifacts when modifying
          draft: true
          tag: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          commit: ${{ github.sha }} # need commit because tag doesn't exist yet
          body: |
            Nightly pre-release build of `${{ github.ref_name }}` on ${{ env.DATE }}.
            This build is for development purposes and not intended for production use.
      
    outputs:
      releaseId: ${{ steps.release.outputs.id }}
      releaseUploadUrl: ${{ steps.release.outputs.upload_url }}
      tagName: ${{ env.TAG_NAME }}

  build-release:
    name: Build Release
    needs: create-release
    uses: ./.github/workflows/build-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseUploadUrl: ${{ needs.create-release.outputs.releaseUploadUrl }}
      releaseVersion: ${{ needs.create-release.outputs.tagName }}

  test-release:
    name: Test Draft Release
    needs: [create-release, build-release]
    uses: ./.github/workflows/test-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseVersion: ${{ needs.create-release.outputs.tagName }}
      serverUrl: https://api.staging.cloudtruth.io
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}

  make-prerelease:
    name: Make Pre-Release
    needs: [create-release, build-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      # move new release from draft to pre-release
      - uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: true
          allowUpdates: true
          omitBody: true
          omitName: true
          tag: ${{ needs.create-release.outputs.tagName }}
          commit: ${{ github.sha }}

      # rotate out old nightly releases
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tag_pattern: nightly
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      



  
