---
name: Nightly Test

# This runs the full suite of tests on all platforms. CI has been changed to run a subset of tests
# on each platform to get full coverage, but not on each platform.

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Nightly Release]
    types:
        - completed

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test-staging.yml
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    with:
      runsOn: ${{ matrix.os }}
      releaseVersion: nightly-staging
    secrets: inherit
