---
name: Nightly
run-name: Nightly Release

on:
  workflow_dispatch:

jobs:
  create-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
  
    steps:
      - name: Create tag name
        shell: bash
        run: echo "TAG_NAME=nightly-staging-$(date +%d-%m-%Y)" >> $GITHUB_ENV

      - name: Create Draft Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          updateOnlyUnreleased: true # prevent modifying any non-draft non-prerelease
          allowUpdates: true # allow overwriting
          removeArtifacts: true # deletes any existing artifacts when modifying
          draft: true
          tag: ${{ env.TAG_NAME }}
          commit: ${{ github.sha }} # need commit because tag doesn't exist yet
          body: |
            Nightly build with latest code from `${{ github.ref_name }}`.
            This build is only tested against a staging environment and not intended for production use.
      
    outputs:
      releaseId: ${{ steps.release.outputs.id }}
      releaseUploadUrl: ${{ steps.release.outputs.upload_url }}
      tagName: ${{ env.TAG_NAME }}

  build-release:
    name: Build Release
    needs: create-release
    uses: ./.github/workflows/build-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseUploadUrl: ${{ needs.create-release.outputs.releaseUploadUrl }}
      releaseVersion: ${{ needs.create-release.outputs.tagName }}

  test-release:
    name: Test Draft Release
    needs: [create-release, build-release]
    uses: ./.github/workflows/test-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseVersion: ${{ needs.create-release.outputs.tagName }}
      serverUrl: https://api.staging.cloudtruth.io
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}

  # remove draft status and change to pre-release
  make-prerelease:
    name: Make Pre-Release
    needs: [create-release, test-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: always()
    steps:
      - uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: true
          allowUpdates: true
          omitBody: true
          omitName: true
          tag: ${{ needs.create-release.outputs.tagName }}
          commit: ${{ github.sha }}

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tag_pattern: nightly-staging
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      



  
