---
name: Nightly
run-name: Nightly Release

on:
  workflow_dispatch:

jobs:
  create-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
  
    steps:
      - name: Create tag name
        shell: bash
        run: |
          DATE="$(date +%d-%m-%Y)"
          echo DATE=$DATE >> $GITHUB_ENV
          echo TAG_NAME=nightly-staging-$DATE >> $GITHUB_ENV
          echo "RELEASE_NAME=Nightly Staging ($DATE)" >> $GITHUB_ENV

      - name: Create Draft Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # allow overwriting
          removeArtifacts: true # deletes any existing artifacts when modifying
          draft: true
          tag: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          commit: ${{ github.sha }} # need commit because tag doesn't exist yet
          body: |
            Nightly build on ${{ env.DATE }} from `${{ github.ref_name }}`.
            This build is only tested against a staging environment and not intended for production use.
      
    outputs:
      releaseId: ${{ steps.release.outputs.id }}
      releaseUploadUrl: ${{ steps.release.outputs.upload_url }}
      tagName: ${{ env.TAG_NAME }}

  build-release:
    name: Build Release
    needs: create-release
    uses: ./.github/workflows/build-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseUploadUrl: ${{ needs.create-release.outputs.releaseUploadUrl }}
      releaseVersion: ${{ needs.create-release.outputs.tagName }}

  test-release:
    name: Test Draft Release
    needs: [create-release, build-release]
    uses: ./.github/workflows/test-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseVersion: ${{ needs.create-release.outputs.tagName }}
      serverUrl: https://api.staging.cloudtruth.io
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}

  make-prerelease:
    name: Make Pre-Release
    needs: [create-release, build-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      # move new release from draft to pre-release
      - uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: true
          allowUpdates: true
          omitBody: true
          omitName: true
          tag: ${{ needs.create-release.outputs.tagName }}
          commit: ${{ github.sha }}

      ## bump the "nightly-staging" tag to the new release

      ## since there's no easy way to copy a release, we need to download all release assets
      ## and transfer them to the nightly-staging release
      - uses: i3h/download-release-asset@v1
        with:
          owner: cloudtruth
          repo: cloudtruth-cli
          tag: ${{ needs.create-release.outputs.tagName }}
          file: /.*/
          path: assets
          token: ${{ secrets.GITHUB_TOKEN }}

      ## rename asset files to remove the date
      - shell: bash
        working-directory: assets
        run: |
          ls cloudtruth* \
          | sed -E 's/^(.*)-(([0-9]{2}-){2}[0-9]{4})(.*)$/& \1\4/' \
          | xargs -n2 mv 
      
      ## overwrite "nightly-staging" release with the new release assets
      - uses: ncipollo/release-action@v1
        with:
          artifactErrorsFailBuild: true
          allowUpdates: true
          removeArtifacts: true
          draft: false
          prerelease: true
          name: Nightly Staging (latest)
          tag: nightly-staging
          commit: ${{ github.sha }}
          artifacts: assets/*
          body: |
            Latest nightly build from `${{ github.ref_name }}`.
            This build is only tested against a staging environment and not intended for production use.

      # rotate out old nightly releases
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tag_pattern: nightly-staging-
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      



  
