name: Nightly

# This runs the full suite of tests on all platforms. CI has been changed to run a subset of tests
# on each platform to get full coverage, but not on each platform.

on:
  workflow_dispatch:
  schedule:
    # Run full test on a nightly basis -- time is GMT, so do it a bit after midnight ET
    - cron: '37 5 * * *'
jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/test-staging.yml
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    with:
      runsOn: ${{ matrix.os }}
      buildOptions: --release
      testOptions: --release
      testRunnerOptions: --exclude backup
    secrets: inherit

