# This is the legacy production test workflow that is being kept so that GitHub shows
# historical job logs. Use test-production.yml workflow instead
---
name: Production (Historical)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "CLI release version to install"
        required: true
        default: 1.1.8

jobs:
  test:
    name: Basic Integration Test (Production)
    runs-on: macOS-latest

    env:
      CLOUDTRUTH_TEST_FILTER: basic
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READWRITE_CT_API_KEY }}
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.version }}

      - name: CLI installation
        run: |
          sudo ./install.sh --version '${{ inputs.version }}'
          cloudtruth --version

      - name: Prerequisites
        run: make test_prerequisites

      - name: Integration Test
        run: |
          cd tests/pytest
          python3 live_test.py --job-id "prod-${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ATTEMPT}" --filter ${{ env.CLOUDTRUTH_TEST_FILTER }}
