# This runs a small set of basic tests against the production deployment, using the latest released
# CLI image.
---
name: Production
on:
  workflow_dispatch:

jobs:
  test:
    name: Basic Integration Test (Production)
    runs-on: macos-latest

    env:
      CLOUDTRUTH_TEST_FILTER: basic
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READWRITE_CT_API_KEY }}
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v3

      - name: CLI installation
        run: |
          sudo ./install.sh
          cloudtruth --version

      - name: Prerequisites
        run: make test_prerequisites

      - name: Integration Test
        run: |
          cd integration-tests
          python3 live_test.py --job-id "prod-${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ATTEMPT}" --filter ${{ env.CLOUDTRUTH_TEST_FILTER }} --exclude backup --reports
