---
name: Sandbox

on:
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox
    uses: ./.github/workflows/test-production-cargo.yml
    strategy:
      fail-fast: false
      matrix:      
        partition: [1, 2, 3]
          
    with:
      runsOn: macos-latest
      testRunnerOptions: -E 'kind(test) & test(basic)' --partition hash:${{matrix.partition}}/3
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READWRITE_CT_API_KEY}}
