---
name: Sandbox

on:
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox
    uses: ./.github/workflows/test-staging-cargo.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            # options: --partition count:1/3
          - os: macos-latest
            # options: --partition count:2/3
          - os: windows-latest
            # options: --partition count:3/3
          
    with:
      runsOn: ${{ matrix.os }}
      testRunnerOptions: -E 'kind(test) & test(basic)' ${{ matrix.options }}
      releaseVersion: staging
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CT_STAGING_CI_ADMIN_API_KEY }}
