---
name: Sandbox

on:
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox
    uses: ./.github/workflows/test-staging.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            options: --partition hash:1/3 
          - os: ubuntu-latest
            options: --partition hash:2/3
          - os: windows-latest
            options: --partition hash:3/3
    with:
      runsOn: ${{ matrix.os }}
      testRunnerType: cargo
      testRunnerOptions: -E 'kind(test) & test(basic)' ${{ matrix.options }}
      releaseVersion: staging
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CT_STAGING_CI_ADMIN_API_KEY }}
