---
name: Sandbox

on:
  workflow_dispatch:

jobs:
  sandbox:
    name: Sandbox
    uses: ./.github/workflows/test-staging.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, opts: --partition hash:1/3 }
          - { os: macos-latest, opts: --partition hash:2/3 }
          - { os: windows-latest, opts: --partition hash:3/3 }
    with:
      testRunnerType: cargo
      runsOn: ${{ matrix.os }}
      testRunnerOptions: -E 'kind(test) & test(basic)' ${{ matrix.opts }}
      releaseVersion: staging
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CT_STAGING_CI_ADMIN_API_KEY }}
