---
name: Staging Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Create Staging Release
    runs-on: ubuntu-latest
  
    steps:
      - name: Create Draft Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # allow overwriting
          updateOnlyUnreleased: true # prevent modifying any non-draft non-prerelease
          removeArtifacts: true # deletes any existing artifacts when modifying
          draft: true
          # need to set this false initially otherwise GH won't emit a prereleased event at the end 
          prerelease: false 
          tag: staging
          name: Staging Build
          commit: ${{ github.sha }} # need commit because tag doesn't exist yet
          body: |
           This is a pre-release build of latest code from `${{ github.ref_name }}`.
           This build is for development purposes and not intended for production use.
      
    outputs:
      releaseId: ${{ steps.release.outputs.id }}
      releaseUploadUrl: ${{ steps.release.outputs.upload_url }}
      tagName: staging

  build-release:
    name: Build Release
    needs: create-release
    uses: ./.github/workflows/build-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseUploadUrl: ${{ needs.create-release.outputs.releaseUploadUrl }}
      releaseVersion: ${{ needs.create-release.outputs.tagName }}

  test-release:
    name: Test Draft Release
    needs: [create-release, build-release]
    uses: ./.github/workflows/test-release.yml
    with:
      releaseId: ${{ needs.create-release.outputs.releaseId }}
      releaseVersion: ${{ needs.create-release.outputs.tagName }}
      serverUrl: https://api.staging.cloudtruth.io
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}

  make-prerelease:
    name: Make Pre-Release
    needs: [create-release, test-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      # move new release from draft to pre-release
      - uses: ncipollo/release-action@v1
        with:
          draft: false
          prerelease: true
          allowUpdates: true
          omitBody: true
          omitName: true
          tag: ${{ needs.create-release.outputs.tagName }}
          commit: ${{ github.sha }}

      



  
