# This runs a small set of basic tests against the staging deployment, using the latest CLI code
# which has to get built.
---
name: Staging
on:
  workflow_dispatch:

jobs:
  test:
    name: Basic Integration Test (Staging)
    runs-on: ubuntu-latest

    env:
      CLOUDTRUTH_TEST_FILTER: basic
      # these are to run against staging
      CLOUDTRUTH_SERVER_URL: https://api.staging.cloudtruth.io
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}
      RUST_BACKTRACE: 1
      RUST_VERSION: 1.63.0

      CLOUDTRUTH_TEST_BASIC_INTEGRATION_NAME: ct-stage-write@943604981792
      CLOUDTRUTH_TEST_BASIC_BAD_INTEGRATION_NAME: my-missing-integration

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        id: rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true

      - name: Show Rust version and platform details
        run: rustc --version --verbose

      - run: cargo build -r

      - name: Integration Test
        run: |
          cd tests/pytest
          python3 live_test.py --job-id "stage-${GITHUB_RUN_NUMBER}" --filter ${{ env.CLOUDTRUTH_TEST_FILTER }} --exclude backup
