# This runs a small set of basic tests against the staging deployment, using the latest CLI code
# which has to get built.
---
name: Staging
on:
  workflow_dispatch:

jobs:
  test:
    name: Basic Integration Test (Staging)
    uses: ./.github/workflows/test.yml
    with:
      serverUrl: https://api.staging.cloudtruth.io
      testRunnerOptions: --exclude backup --filter basic

    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_STAGING_CONTRIBUTOR }}
