---
name: Nightly Test
run-name: Test Nightly (${{ github.event.client_payload.tagName }})

on:
  repository_dispatch:
    types: [nightly-release]

env:
  CI: true

jobs:
  test-nightly:
    name: Nightly Test

    uses: ./.github/workflows/test-staging.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    with:
      runsOn: ${{ matrix.os }}
      releaseVersion: ${{ github.event.client_payload.tagName }}
      testRunnerOptions: -E 'kind(test)'
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CT_STAGING_CI_ADMIN_API_KEY }}

  cleanup-nightly:
    name: Nightly Cleanup
    needs: test-nightly
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: cloudtruth/cloudtruth-cli

      - run: sh cicd/scripts/install-rust.sh

      - run: sudo ./install.sh --install-prerequisites

      - run: cargo run --release --package xtask -- cleanup --confirm cli-test
