name: Test Staging
on:
  workflow_call:
    inputs:
      artifactId:
        description: An artifact ID containing the CLI executable to test. Either artifactId or releaseVersion should be provided
        type: string
      releaseVersion:
        description: A release tag to download with the install script. Either artifactId or releaseVersion should be provided
        type: string
      testRunnerOptions:
        description: string of command-line options to pass to the test runner
        type: string
      runsOn:
        description: The runner to run the workflow on
        type: string
        default: ubuntu-latest
      rustBacktrace:
        description: Value of the RUST_BACKTRACE variable (default no backtrace)
        type: string
        default: "0"
    secrets:
      CLOUDTRUTH_API_KEY:
        description: "Staging API Key"
        required: true

env:
  CI: true
  # ID to append to test data to avoid name collisions
  JOB_ID: ${{github.repository_id}}-${{github.run_id}}-${{github.run_attempt}}-${{inputs.runsOn}}
  RUST_BACKTRACE: ${{ inputs.rustBacktrace }}
  CLOUDTRUTH_SERVER_URL: https://api.staging.cloudtruth.io
  CLOUDTRUTH_API_KEY: ${{ secrets.CLOUDTRUTH_API_KEY }}
  TEST_ARCHIVE_FILE: integration-test-${{inputs.runsOn}}.tar.zst


jobs:
  cargo-test:
    name: CLI Test (staging, cargo-nextest)
    runs-on: ${{ inputs.runsOn }}

    steps:
      - shell: bash
        if: | 
          inputs.artifactId == '' && inputs.releaseVersion == '' ||
          inputs.artifactId != '' && inputs.releaseVersion != ''
        run: | 
          echo "Workflow input error: exactly one of 'artifactId' or 'releaseVersion' must be provided"
          exit 1

      - uses: actions/checkout@v3
        with:
          repository: cloudtruth/cloudtruth-cli
          ref: ${{ inputs.releaseVersion }}

      - run: sh xtask/scripts/install-rust.sh

      - uses: taiki-e/install-action@cargo-nextest

      - uses: actions/download-artifact@v3
        if: inputs.artifactId
        with:
          name: ${{ inputs.artifactId }}
          path: target

      # upload-artifact does not preserve permissions
      - shell: bash
        if: inputs.artifactId
        run: find target -type f -name 'cloudtruth*' -exec chmod +x {} +

      # fetch pre-built integration test archive
      - uses: dsaltares/fetch-gh-release-asset@master
        if: inputs.releaseVersion 
        with:
          version: tags/${{ inputs.releaseVersion }}
          file: ${{ env.TEST_ARCHIVE_FILE }}

      - name: Setup test variables
        shell: bash
        run: |
          cat integration-tests/staging.env >> $GITHUB_ENV

      # run from pre-built archive
      - name: E2E Test
        if: inputs.releaseVersion
        shell: bash
        run: cargo nextest run --profile ci --archive-file "$TEST_ARCHIVE_FILE" ${{ inputs.testRunnerOptions }}

      # build and run
      - name: E2E Test
        if: inputs.artifactId
        shell: bash
        run: cargo nextest run --profile ci --all-features --tests ${{ inputs.testRunnerOptions }}

