---
name: 'Test Release'
on:
  workflow_call:
    inputs:
      releaseId:
        description: 'Release ID returned by create-release action'
        type: string
        required: true
      releaseVersion:
        description: 'CLI Release Version (defaults to tag name)'
        type: string
        default: ${{ github.ref_name }}
    secrets:
      GITHUB_TOKEN:
        description: GitHub API Token
        required: true
      CI_ACCT_READONLY_CT_API_KEY:
        description: CloudTruth API Key
        required: true

jobs:
  test-alpine:
    runs-on: ubuntu-latest
    needs: [ 'build-release' ]
    env:
      # github release info
      CT_DOWNLOAD_RELEASE_ID: ${{ inputs.releaseId }}
      CT_DOWNLOAD_VERSION: ${{ inputs.releaseVersion }}

      # Need auth-token to download from draft release
      CT_DOWNLOAD_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: alpine-3.13
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.alpine-3.13 \
             -t cloudtruth:alpine-3.13
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:alpine-3.13 cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

      - name: alpine-3.12
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.alpine-3.12 \
             -t cloudtruth:alpine-3.12
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:alpine-3.12 cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

  test-rockylinux:
    runs-on: ubuntu-latest
    needs: [ 'build-release' ]
    env:
      # github release info
      CT_DOWNLOAD_RELEASE_ID: ${{ inputs.releaseId }}
      CT_DOWNLOAD_VERSION: ${{ inputs.releaseVersion }}

      # Need auth-token to download from draft release
      CT_DOWNLOAD_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: rockylinux-8
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.rockylinux-8 \
             -t cloudtruth:rockylinux-8
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:rockylinux-8 cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

  test-debian:
    runs-on: ubuntu-latest
    needs: [ 'build-release' ]
    env:
      # github release info
      CT_DOWNLOAD_RELEASE_ID: ${{ inputs.releaseId }}
      CT_DOWNLOAD_VERSION: ${{ inputs.releaseVersion }}

      # Need auth-token to download from draft release
      CT_DOWNLOAD_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: debian-bullseye-slim
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.debian-bullseye-slim \
             -t cloudtruth:debian-bullseye-slim
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:debian-bullseye-slim cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

      - name: debian-buster-slim
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.debian-buster-slim \
             -t cloudtruth:debian-buster-slim
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:debian-buster-slim cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

      - name: debian-jessie-slim
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.debian-jessie-slim \
             -t cloudtruth:debian-jessie-slim
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:debian-jessie-slim cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

  test-macOS:
    runs-on: macOS-latest
    needs: [ 'build-release' ]
    env:
      # github release info
      CT_DOWNLOAD_RELEASE_ID: ${{ inputs.releaseId }}
      CT_DOWNLOAD_VERSION: ${{ inputs.releaseVersion }}

      # Need auth-token to download from draft release
      CT_DOWNLOAD_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: macOS-latest
        run: |
          sudo ./install.sh --auth-token "${CT_DOWNLOAD_AUTH_TOKEN}" --release-id "${CT_DOWNLOAD_RELEASE_ID}" --version "${CT_DOWNLOAD_VERSION}"
          cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep "${CT_TEST_PARAM}" | grep "${CT_TEST_VALUE}"

  test-ubuntu:
    runs-on: ubuntu-latest
    needs: [ 'build-release' ]
    env:
      # github release info
      CT_DOWNLOAD_RELEASE_ID: ${{ inputs.releaseId }}
      CT_DOWNLOAD_VERSION: ${{ inputs.releaseVersion }}

      # Need auth-token to download from draft release
      CT_DOWNLOAD_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: ubuntu-focal
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.ubuntu-focal \
             -t cloudtruth:ubuntu-focal
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:ubuntu-focal cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

      - name: ubuntu-bionic
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.ubuntu-bionic \
             -t cloudtruth:ubuntu-bionic
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:ubuntu-bionic cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

      - name: ubuntu-xenial
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.ubuntu-xenial \
             -t cloudtruth:ubuntu-xenial
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:ubuntu-xenial cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

      - name: ubuntu-trusty
        run: |
          docker build . \
            --build-arg DOWNLOAD_AUTH_TOKEN="${CT_DOWNLOAD_AUTH_TOKEN}" \
            --build-arg DOWNLOAD_RELEASE_ID="${CT_DOWNLOAD_RELEASE_ID}" \
            --build-arg DOWNLOAD_VERSION="${CT_DOWNLOAD_VERSION}" \
             -f build/docker/test-release/Dockerfile.ubuntu-trusty \
             -t cloudtruth:ubuntu-trusty
          docker run -e CLOUDTRUTH_API_KEY --rm -v $(pwd):/truth -t cloudtruth:ubuntu-trusty cloudtruth --project ${CT_TEST_PROJECT} parameters list -v | grep ${CT_TEST_PARAM} | grep ${CT_TEST_VALUE}

  test-windows:
    runs-on: windows-latest
    needs: [ 'build-release' ]
    env:
      # github release info
      CT_DOWNLOAD_RELEASE_ID: ${{ inputs.releaseId }}
      CT_DOWNLOAD_VERSION: ${{ inputs.releaseVersion }}

      # Need auth-token to download from draft release
      CT_DOWNLOAD_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # These values are used for running the CLI command
      CLOUDTRUTH_API_KEY: ${{ secrets.CI_ACCT_READONLY_CT_API_KEY }}
      CT_TEST_PROJECT: TruthStrap
      CT_TEST_PARAM: INTEGRATION_TEST_RESULT
      CT_TEST_VALUE: Speicla

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: windows-latest
        shell: pwsh
        run: |
          $InformationPreference = 'Continue'
          New-Alias grep findstr
          $ctExe = .\install.ps1 -authToken "$ENV:CT_DOWNLOAD_AUTH_TOKEN" -releaseId "$ENV:CT_DOWNLOAD_RELEASE_ID" -version "$ENV:CT_DOWNLOAD_VERSION"
          & $ctExe --project "$ENV:CT_TEST_PROJECT" parameters list -v | grep "$ENV:CT_TEST_PARAM" | grep "$ENV:CT_TEST_VALUE"
