---
name: Nightly Test
run-name: Test Nightly (${{ github.event.client_payload.tagName }})

on:
  repository_dispatch:
    types: [nightly-release]

env:
  CI: true

jobs:
  test-nightly:
    name: Nightly Test

    uses: ./.github/workflows/test-staging.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    with:
      runsOn: ${{ matrix.os }}
      releaseVersion: ${{ github.event.client_payload.tagName }}
      testRunnerOptions: -E 'kind(test)'
    secrets:
      CLOUDTRUTH_API_KEY: ${{ secrets.CT_STAGING_CI_ADMIN_API_KEY }}