# This runs a small set of basic tests against the production deployment, using the latest released
# CLI image.
---
  name: Test Production
  on:
    workflow_call:
      inputs:
        releaseVersion:
          description: CLI release version to download and install
          type: string
          default: '1.2.7'
        runsOn:
          description: The runner to run the workflow on
          type: string
          default: macos-latest
        testRunnerOptions:
          description: string of command-line options to pass to the test runner
          type: string
      secrets:
        CLOUDTRUTH_API_KEY:
          description: "Production API Key"
          required: true

  env:
    CI: true

  jobs:
    test:
      name: CLI Test (production)
      runs-on: ${{ inputs.runsOn }}

      defaults:
        run:
          shell: bash

      env:
        CLOUDTRUTH_API_KEY: ${{ secrets.CLOUDTRUTH_API_KEY }}
        JOB_ID: ${{github.repository}}-${{github.run_id}}-${{github.run_attempt}}-cli-prod
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
        TEST_ARCHIVE_FILE: integration-test-${{inputs.runsOn}}.tar.zst

      steps:
        - uses: actions/checkout@v4
          with:
            repository: cloudtruth/cloudtruth-cli

        - run: sh cicd/scripts/install-rust.sh

        - uses: taiki-e/install-action@cargo-nextest

        # fetch pre-built integration test archive
        - uses: dsaltares/fetch-gh-release-asset@1.1.1
          with:
            repo: cloudtruth/cloudtruth-cli
            version: tags/${{ env.RELEASE_VERSION }}
            file: ${{ env.TEST_ARCHIVE_FILE }}

        # run from pre-built archive
        - name: E2E Test
          run: cargo nextest run --profile ci --archive-file "$TEST_ARCHIVE_FILE" ${{ inputs.testRunnerOptions }} --workspace-remap "${GITHUB_WORKSPACE}"
